### ISSUE TITLE
Game can't make up its mind reporting if a move is super effective or not very effective

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#245] opened 2023-01-12 07:24 UTC
[Click](https://www.youtube.com/watch?v=55EZvhGGMiY)

I found this while I was actually testing something else. For pokemon like Jolteon with focus energy there actually seems to be a very small chance that attacks do not critically hit. What's the explanation there? crit rate is effectively 101.5625% but it's not functioning that way.

**Comment by jojobear13** [comment] 2023-01-18 21:48
I found the problem. The damage effectiveness multiplier only resets at the start of executing a move. This is fine if you plan to do the same damage only once like in vanilla Gen 1. But when I made it so that multiple-hitting attacks can crit and do variable damage with each attack, the multiplier never resets. In fact, it keeps adding to itself and eventually overflows back not not-very-effective. 

What's weird is that it is more efficient and blatantly obvious to reset the damage multiplier in the function that actually calculates it. Makes me wonder why Morimoto didn't catch that.

**Comment by jojobear13** [comment] 2023-01-18 22:10
As for not hitting 100% crit rate, there is a line of code in RBY battle engine that caps the critical hit rate at 255 out of 256. I thought it was a bug until I noticed that the same thing was done in the readjusted code for Stadium.

**Comment by DiabloStorm** [comment] 2023-01-19 22:49
> As for not hitting 100% crit rate, there is a line of code in RBY battle engine that caps the critical hit rate at 255 out of 256. I thought it was a bug until I noticed that the same thing was done in the readjusted code for Stadium.

So are you intending to keep or fix this limitation similar to how DV limitations were fixed? (reworked?)

**Comment by jojobear13** [comment] 2023-01-27 19:43
Fixed in ca13d321a8bbfd582658fe476a32ae13c6aa63a9

>So are you intending to keep or fix this limitation similar to how DV limitations were fixed? (reworked?)

Unsure. This will go under a different internal discussion about whether or not to align the hack's crit-rate mechanics to follow Stadium-1. It's algebra is a little different and results in the lowest speed tiers getting a buff and the highest speed tiers getting a nerf.

**Comment by DiabloStorm** [comment] 2023-01-27 19:46
I'm actually playing stadium for the first time, can you explain the difference?

**Comment by jojobear13** [comment] 2023-01-27 21:58
In vanilla:
- The base accuracy of a move is a number between 0 and 255. A move hits if a pseudorandom number R[0, 255] < the base accuracy. Naturally if 255 is rolled against a move with 255 accuracy, then the move misses. 
- The base crit chance C = (0.5 * base speed). A critical hit occurs if a pseudorandom number R[0, 255] < C. Naturally if 255 is rolled against a move with C = 255, then there is no critical hit. The base crit chance for Slowpoke is about 1% while for Electrode it is 27%

In Stadium:
- The base accuracy of a move is a number between 0 and 255. A move hits if a pseudorandom number R[0, **255**] < the base accuracy. It is now impossible to roll a 255 and miss with a move that has 255 accuracy.
- The base crit chance C = [0.25 * (base speed + 76)]. A critical hit occurs if a pseudorandom number R[0, 255] < C. Naturally if 255 is rolled against a move with C = 255, then there is no critical hit. HAL Laboratory purposefully fixed the former but left the 1/256 chance for the latter. Furthermore, this adjust formula means that Slowpoke has a base crit chance of 7.9% while an Electrode has a base crit chance of 21%.


It's not like HAL Laboratory made arbitrary decisions either. Stadium-Japan and Stadium-1 are given a lot of weight when determining intent because they were made for tournament play (particularly based on the rules for Nintendo Cup '97 and '98). That said, they are not treated as dogma. This hack does deviate from them intentionally for certain things. The big one that comes to mind is Hyper Beam requiring recharge on a miss; literally everyone said that it "fucking sucked" even though that's truly how it was intended to work in gen 1.

Me personally? I'm indifferent either way. 1/256 is only an extra 0.4% to crit.

**Closed** 2023-09-19 03:25 UTC
Labels: bug, resolved - next patch
