### ISSUE TITLE
Individual Party Icons

### ISSUE THREAD

**Issue by jammer506** [jojobear13/shinpokered#284] opened 2023-09-28 08:47 UTC
Curious if this would be a possibility since the documentation for Pret's Pokemon Red Disassembly is available. Thank you!

**Comment by jojobear13** [comment] 2023-09-29 05:46
Possible? Yes. But will not implement. It is out of scope for shinpokered to be altering the art direction unless it is something that was intended for Pokemon Red, Green, or Blue (such as the Spaceworld back sprites largely being intended to match with Blue's front sprites).

**Closed by jojobear13** 2023-09-29 05:46 UTC
Labels: suggestion
