### ISSUE TITLE
Clipping through walls?

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#251] opened 2023-01-19 21:56 UTC
[Click](https://www.youtube.com/watch?v=Sl6fK4ddp-A)
Cerulean Cave

**Comment by jojobear13** [comment] 2023-01-19 22:20
note to self. Tiles 07 and 17 do not have collision on cave tileset

**Comment by jojobear13** [comment] 2023-01-19 23:33
Problem confirmed to be a vanilla bug.

![image](https://user-images.githubusercontent.com/47074297/213585412-22a08389-352c-426b-95c1-28d7d38d72e4.png)

**Comment by DiabloStorm** [comment] 2023-01-19 23:37
Huh. interesting.

**Comment by jojobear13** [comment] 2023-01-19 23:40
Notes to self. Tile collision coordinate structure. Red are tile coordinates occupied by player. Coordinate 8,9 is defined as the player's tile. Yellow are the tiles that are checked for collision.

![image](https://user-images.githubusercontent.com/47074297/213585943-1f32e54a-d398-40f2-97e1-cd1f124bd457.png)

**Comment by DiabloStorm** [comment] 2023-01-19 23:45
So. Another thing about collision. What do you think about the vanilla game playing the "thump" sound when exiting buildings?

Duno if you noticed it.

Example:
Building entrance is one tile, building exit is usually 2 tiles, I think if you exit the tile other than the one it puts you on, the "thump" plays but you still go through the door.

**Comment by jojobear13** [comment] 2023-01-20 02:21
Looks like I might be able to check for the warp flag and deny the *thump* from playing. 
![image](https://user-images.githubusercontent.com/47074297/213604357-07292269-b1c2-4c28-8931-18f71dc9c248.png)

**Comment by DiabloStorm** [comment] 2023-01-20 02:27
> Looks like I might be able to check for the warp flag and deny the _thump_ from playing. ![image](https://user-images.githubusercontent.com/47074297/213604357-07292269-b1c2-4c28-8931-18f71dc9c248.png)

It's just an oddity I noticed. Do what you will.

**Comment by jojobear13** [comment] 2023-01-27 20:04
fixed in 7f87439982982b4b1a3e4465f17953af672d8520 as well as aed74701c88cb44499878e1baf02d0a4a622d8d5

**Closed** 2023-09-19 03:25 UTC
Labels: bug, retail, resolved - next patch
