### ISSUE TITLE
Tiny request regarding Old Rod.

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#255] opened 2023-01-28 02:22 UTC
>- The Old Rod now randomly acts as a Good rod 50% of the time.

Would it be possible to implement a toggle to turn this off?

The reasoning is purely personal preference, as I think goldeen/seaking are immensely less relevant than Magikarp/Gyarados.

I'm trying to DV farm a magikarp and all these goldeen are just getting in the way. (yes I'm ignoring that seller that gives me the 'karp with DVs skewed higher, I don't feel like using that, or m.gene, or punnett square, it feels too much like cheating as I want to find my own with the intention of potentially transferring to gen 2 where the DV battle this game provides isn't present)

Anyway, if this were to change, I'll likely have found my magikarp before then, but having more options is generally nice.

**Comment by DiabloStorm** [comment] 2023-01-28 02:29
Yeah...
![bgb00007 (3)](https://user-images.githubusercontent.com/63818362/215237564-e4d96fd5-9374-4cd0-a709-1fcc74cc2e75.gif)
quite literally minutes after posting lol

**Comment by jojobear13** [comment] 2023-01-28 19:31
The current dev build reworks some things. 

Here is how it’s working in 1.23.11.

The Old Rod can fish up two kinds of pokemon (depending on the current map).
- Magikarp or Goldeen
- Magikarp or Poliwag

This works by expanding the fishing list.

What if I expanded the old rod a little more so that some maps will only give magikarp?

**Comment by DiabloStorm** [comment] 2023-01-28 22:25
That's alright, and so was your previous idea. The previous one could be expanded to regain the previous function of good rod also. I admittedly have not fished much up until now but my understanding is that it's an expanded list of 8 for good rod, which in my specific circumstance, if i was looking for a specific pokemon with specific dvs, the encounters would be more saturated than before with pokemon you aren't looking for.

**Comment by jojobear13** [comment] 2023-01-29 05:03
Okay, so here is how things work in Vanilla:
- Old rod always generates a lvl 5 magikarp from the item's execution function.
- Good rod has a 50% chance of an encounter: Either a lvl 10 goldeen or a lvl 10 poliwag from the item's execution function.
- Super rod works like regular wild encounters and references pre-programmed Groups of 4 pokemon that get assigned to different maps. **If a map does not have a super rod list assigned to it, then you won't hook anything.**

>Unrelated but, I just thought of this...why was fishing removed from Lorelai's area? I was actually going to use it to save on potions and use recover but discovered the fish were removed, was it to prevent that? lol

See my bold above. Lorelei's area works with Old and Good rods because they generate encounters straight from their execution, but her map doesn't have a Super Rod group assigned to it.

It really looks to me that Gamefreak spent all their effort on implementing the Super Rod and the other two were afterthoughts.

Here's how it works in my dev build as of commit adbdd98595eeea80918322ebb44fd1caf774877b:
- All rods randomly add some extra levels to what's being hooked for variety's sake.
- Old Rod has a 50% chance of giving poliwag or goldeen off the Good Rod list. Otherwise gives magikarp. Quickly hold B to only get magikarp.
- Super rod mechanics are untouched except for me adding Lapras to Group 6 and tweaking Group 22.
- Good Rod has a 50% chance of an encounter. The encounter table is expanded to 9 slots populated with 7 species: poliwag, goldeen, horsea, krabby, psyduck, shellder, and tentacool. **BUT** not all are accessible all the time. The last two bits of the current map value are used to calculate the starting offset within the good rod table, of which there is a 50% chance of jumping 4 slots forward and another 50% chance of jumping 1 slot forward. This has the effect of algorithmically creating 4 separate groups for the Good Rod and automatically assigning every map its own group.
  - Poliwag, Poliwag Horsea, Krabby  -->  map value ends in %00 (such a Pallet Town)
  - Poliwag, Krabby, Goldeen, Psyduck  -->  map value ends in %01 (such as Viridian City)
  - Goldeen, Goldeen, Psyduck, Shellder  -->  map value ends in %10 (such as Celadon City)
  - Goldeen, Shellder, Horsea, Tentacool  -->  map value ends in %11 (such as Route 12)


>Was anything changed with dv spreads for fished pokemon?

No. Fished pokemon are treated the exact same as wild encounters except for some slightly different battle text. RNGesus giveth and RNGesus taketh away.

>I'm hoping, besides the changes I'm aware of (all 65535 DVs possible, m.gene, punnett square, gift/prize DV skew, post E4 safari zone dv skew, L100 chansey) everything else was left vanilla?

Yeah, I think that's everything.

>Speaking of which, what went into unlocking all 65535 DVs? 

Trashing Gamefreak's RNG function and implementing something else. [Here is all the code that Vanilla uses to get a pseudo-random number](https://github.com/pret/pokered/blob/e076ee0a40b2a21183e2cc535519e64b706b5407/engine/math/random.asm#L1). There is also a [video by Crystal_](https://www.youtube.com/watch?v=BcIxMyf8yHY) that explains in detail. Basically, it reads the Gameboy's divider register for a random value and then subtracts that from its last value to get a second random value that quickly becomes uncorrelated. It's fast, it's light on memory, and it's "good enough" assuming that there is some entropic factor between updates (like the time between button presses) and you think that people will never figure out that DVs exist (reasonable in a time before widespread datamining of games on the internet). The problem is that successive calls for random numbers with no entropy in-between quickly make the results settle into a predictive pattern where certain outcomes become impossible.

For a long time the solution I had was to switch to the RNG engine used in the Polished Crystal rom hack by Rangi42. It worked well, but I felt it was a little too over-engineered for my purposes. For example, there's this whole feature it had (which I never activated) that queues-up random numbers so that you cannot scum with save states. As of the v1.23.09 beta, I switched to a Marsaglia XOR-Shift RNG method that was adapted by Patrik Rak for Z80-style CPUs and released into public domain. It's a much lighter, faster, and more streamlined method that uses four different seed values. 

For seed values, I read four HRAM locations when the game first starts. On real hardware, these values on first boot are random due to the nature of semiconductor physics (even being affected by the ambient temperature). Some emulators, like BGB, replicate this by populating the emulated RAM with its own pseudo-random number generator. Most emulators don't and just zero it all out on startup (breaks things because all-zero seeds are not valid), so I made sure to always change a seed value of $00 to $01.

**Comment by DiabloStorm** [comment] 2023-02-01 04:47
Interestingly smogon had a link to a chart and a tool showcasing area ["encounter slots" (rates?)](http://wiki.pokemonspeedruns.com/index.php?title=Pok%C3%A9mon_Red/Blue/Yellow_Encounter_Slots) and now i'm wondering if someone somewhere compiled something like this for gen 2 because now I'm curious if there are limitations there as well but I can't find any resources, and any attempt to google up "encounter rates" for gen 2 seemingly doesn't yield the type of "encounter rate" i'm referring to here.

**Comment by jojobear13** [comment] 2023-02-01 20:29
The "Hold B" solution is now in commit adbdd98595eeea80918322ebb44fd1caf774877b

As for gen 2, [smogon has some chatter about it also having the same issue](https://www.smogon.com/forums/threads/15-15-15-15-dvs-are-impossible-in-most-cases.3573219/).

**Comment by jojobear13** [comment] 2023-02-02 06:24
beta patches 1.23.12 are uploaded which addresses this issue and a bunch of others made since Nov 2022.

**Closed** 2023-09-19 03:25 UTC
Labels: enhancement, resolved - next patch
