### ISSUE TITLE
Game crashes when in stats menu for Nidoran♂ and Nidoran♀

### ISSUE THREAD

**Issue by twhiching** [jojobear13/shinpokered#52] opened 2020-08-12 03:13 UTC
When trying to view the stats for Nidoran♂ or Nidoran♀ the game crashes once the second page of the stats menu is about to display. Garbage text is displayed on screen and then the system locks up. I've caught  Nidoran♂ and Nidoran♀ on route 22 near the beginning of the game. I've tested and replicated the bug both on bgb and on real hardware through the use of an everdrive x7. I've used two different saves and was able to reproduce the bug. Viewing the stats of other Pokemon does not seem to crash the game. Below you can see a gif with the bug in action. The save state for the bug is provided as well.
![pokemon red shin 2 0](https://user-images.githubusercontent.com/53712543/89970924-e4e0e280-dc27-11ea-9372-4e552f7bc25c.gif)
[Pokémon Red Shin 2.0.sav.zip](https://github.com/jojobear13/shinpokered/files/5060401/Pokemon.Red.Shin.2.0.sav.zip)

**Comment by jojobear13** [comment] 2020-08-12 09:40
Caused by a stack error. Improper placement of "pop de" in status_screen.asm file. Problem will affect any pokemon that is all-male, all-female, or sexless while the symbols are toggled on. The below code shows the proper placement of "pop de".

```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;joenote - print gender symbol here
	CheckEvent EVENT_90E
	jr z, .nosymbol
	push de
	ld a, [wLoadedMonSpecies]
	ld d, a
	ld a, [wUnusedD722]
	ld e, a
	callba DetermineMonGender
	ld a, d
	pop de
	and a
	jr z, .nosymbol
	coord hl, 9, 3
	ld [hl], a
.nosymbol
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```

Fix has been applied to the master_dev branch and is slated for v1.15.

**Closed by jojobear13** 2020-08-12 09:40 UTC
