### ISSUE TITLE
Poison damage happened twice when opponent switched Pokemon

### ISSUE THREAD

**Issue by aspacek** [jojobear13/shinpokered#82] opened 2021-01-05 11:20 UTC
Hi, sorry if this isn't the right place to post this, but I thought it might be worth mentioning.

I was playing the lite branch mod with Pokemon Red, my Pokemon was poisoned, the opponent switched their Pokemon, my Pokemon took poison damage after they switched, then my Pokemon attacked and took poison damage again. I'm pretty sure that's not how poison damage should be working, my Pokemon shouldn't have taken poison damage after the opponent switched their Pokemon, it should have only happened after my Pokemon attacked.

If the details help:
Fighting the Meowth Lass on Route 8 west of Lavender Town (she's 3rd from the top in that vertical row of 4 trainers). My Onix was poisoned, she switched her Meowth, and then the double poison damage happened.

Thanks!

**Comment by aspacek** [comment] 2021-01-05 11:23
To add, it just happened again with another trainer.

**Comment by jojobear13** [comment] 2021-01-05 21:14
Confirmed and isolated. Working on a solution.

**Comment by jojobear13** [comment] 2021-01-05 22:07
Problem diagnosed. 

Poison/burn/leechseed damage is checked twice, once for each combatant, in order of move priority. 

If the player is to go first and the enemy switches or uses an item, then the order is [enemy switch or item-->execute player move-->player poison damage-->enemy acted already-->enemy poison damage]. This works as intended.

If the enemy is to go first and switches or uses an item, then the order is [enemy switch or item-->enemy acted already-->enemy poison damage-->execute player move-->player poison damage]. This is not working as intended. The value H_WHOSETURN is cleared to 00 (indicating the player's turn) after an AI trainer switches instead of remaining as 01 (the enemy's turn), so poison/burn/leechseed damage is checked for the player twice and not at all for the enemy.

This is fixed in commit 4ca2d9c7e19defe93e26199df61c1b6c828f59fb and is slated for the next release.

**Closed** 2021-01-30 08:12 UTC
Labels: bug
