### ISSUE TITLE
Bug: Poke Flute inconsistency

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#274] opened 2023-06-24 06:37 UTC
**What emulator and/or hardware are you are using?**
bgb 1.5.9.w64

**What version of this project are you using?**
built from source master_dev commit https://github.com/jojobear13/shinpokered/commit/783681261a853c8a33d7b607b38166467e1c6c18

**What is the problem you encountered?**
If you use the Poke Flute immediately after putting an enemy mon to sleep, it will give the "Now that's a catchy tune!" message. If you wait a turn, it will give the "All sleeping Pokemon woke up." message.

https://github.com/jojobear13/shinpokered/assets/52078365/c9e0be64-6f5b-4700-b402-b56554c17cdd

(NB: The same thing happens if your mon goes second.)

**Comment by jojobear13** [comment] 2023-06-25 19:51
Confirmed to be reproducible in the vanilla games.

**Comment by jojobear13** [comment] 2023-06-25 20:29
Fixed via 178936fa. This bug is caused by an oversight in the pokeflute function. The message displayed is determined by the value of wWereAnyMonsAsleep, and this byte only gets set by the function WakeUpEntireParty. But the WakeUpEntireParty function only gets run for the player's party and an enemy trainer party; never for a wild pokemon. This can cause some mismatches under various conditions.

**Closed** 2023-09-19 03:25 UTC
Labels: bug, retail, resolved - next patch
