### ISSUE TITLE
Multiple Minor Issues & Suggestions

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#148] opened 2021-08-10 01:41 UTC
I still have two areas to check but it might take some time to get back to the game so I'll post here what I have:

1) Agility doesn't have animation. I think this was the case in the original version as well, but for the Master version maybe a Gen-2 animation could be used.
2) The first trainer in Route 19 entering from Fuchsia City has the same pre-battle and post-battle text. This might or might not be a bug but I think his text is more suitable as post-battle so there may be some typo in the variable names there.
3) Passing the water entrance between F4 and  F5 in Seafoam Islands doesn't allow the player to go back unless he takes a step first. This is the same behavior as going inside the F11 elevator in Silph Co. (it doesn't happen with other floors). So the same patch might be needed.
4) For me the game crashed once. This happened by taking a few steps after delivering the Dome Fossil to the lab. I am using mGBA, so it might be emulator-related.
5) Opponent PKMN seems to always hit a switch in PKMN of the player in the turn it was switched in. Specifically, I tried lowering the opponent's accuracy by six stages, and the switched PKMN, the opponent's move hit. In the entire playthrough, I can't remember the opponent PKMN missing a hit after the player switched. I also remember I had the same feeling in the old days with PKMN Stadium 1. It might be worth an investigation (or my luck is just that bad).
6) Opponent PKMN use Selfdestruct or Explosion even if the move is sure to fail, even if they have other moves available. Specifically, there are two cases I can verify: a) Opponent's PKMN uses Selfdestruct in Ghost-types, although not from the start of the battle, b) Opponent's PKMN uses Selfdestruct even if its speed is higher than player's PKMN and player's PKMN used Fly or Dig in the previous turn.

I'll try to update the post with more issues as soon as I can get back to the game. Could luck with those and let me know if I can help more.

**Comment by wisp92** [comment] 2021-08-10 01:49
Also, one more enhancement I just thought of. Since opponents can now switch PKMN properly you may want to implement a new difficulty option so that the users can play under competitive rules, e.g., only one PKMN is allowed to be asleep and so on, I think the complete list can be found in Smogon.com.

**Comment by jojobear13** [comment] 2021-08-10 04:19
On #4 - I noticed you've been having strange issues pop up from time to time that I cannot verify. This might indeed be related to your emulator. It could also be that you need to re-patch over a fresh vanilla rom. The only explanation I can think of is that certain address calls are corrupted.

On #2 - I think you are referring to the first swimmer in the water. The pre and post battle texts are actually different, but basically the same thing is being said. Not sure why Nob Ogasawara chose that.
`_Route19BattleText6::
	text "I look at the"
	line "sea to forget!"
	done

_Route19EndBattleText6::
	text "Ooh!"
	line "Traumatic!"
	prompt

_Route19AfterBattleText6::
	text "I'm looking at the"
	line "sea to forget!"
	done`
It might be a reference or a pun that works better in Japanese.

On #5 - I ran a few recreations and confirmed that no overflows were happening with accuracy debuffs. I can get enemy trainer mons to miss 100 accuracy moves on switch-ins if they have an accuracy debuff. You likely are just remembering when you get hosed by the RNG, but I have found that habitually hammering the A button will cause the RNG to produce less-random results. This is because the time between button presses is used to inject real randomness into a non-random system. Hammer the A button like a fiend and you end up having the same small range of milliseconds between each press.

On #6 - Not everyone fights like a gym leader. AI is separated into layers, and different trainer types have different layers. Trainers that do not have AI layer 3 (typically inexperienced or unintelligent trainers) will not know how to type-match, so they are allowed to do things like use explosion on ghost types. For example, Rockets and Bikers will do this because they are dumb ne'er-do-wells. Checking for speed and fly/dig status is a good one that I didn't think about, so I'll add that.

On #1 - Yes, Agility is SFX-only with no animation. I'll play around with giving it a glare or double-team visual effect and see if I can get something to work.

On clauses: This hack isn't really meant to support the smogon meta. There are other projects that do that kind of thing better. That said, Pokemon Stadium invented the Sleep and Freeze clauses. I'd be willing to look into how to implement those.

**Comment by wisp92** [comment] 2021-08-10 04:27
#4 Thanks for that I'll try to play once in a different emulator and see what happens.
#5 That may well be the case, I tend to press the buttons a lot. Do you know if the same method was used in PKMN Stadium?

I totally get it for Smogon, but it's such a fun mod especially with the scaling and the new battle mechanics that I feel it is really ready for more seasoned players that are looking to extra challenges (like myself). Thank you again for the awesome mod. I am also looking forward to your Crystal mod by the way.

**Comment by jojobear13** [comment] 2021-08-10 04:55
>Thank you again for the awesome mod. I am also looking forward to your Crystal mod by the way.
Thanks, I appreciate it.

> Do you know if the same method was used in PKMN Stadium?
Stadium does not use the same method. RNG implementation is largely going to be informed by the processor of the console. The N64 used a very modern 64-bit cpu. The console released in 1996 with a processor is based on the MIPS Technologies R4300i from 1995. Compare this to the gameboy; it came out in 1989 with a processor based on the 8-bit Zilog Z80 from 1976!

The gameboy uses an outdated and underpowered cpu that was derided by its internal dev team. It's RNG kinda blows. However, this design decision is helped lower battery consumption and reduced overall cost. Kind of a big deal when your competition is the Game Gear that costs $60 more and eats through batteries 15x as fast.

**Closed** 2021-08-10 05:45 UTC
Labels: wontfix
